### ISSUE TITLE
TOML `SerialzationFormat` fails for `GdsLibrary`

### ISSUE THREAD

**Issue by dan-fritchman** [dan-fritchman/Layout21#33]

**Comment by dan-fritchman** [comment]
Rooting around `GdsLibrary`, without testing this at all, I have a bet, and that bet is, it's this date & time stuff:

```rust
/// # Gds Date & Time
///
/// In typical cases, a wrapper around a [`NaiveDateTime`] with custom serialization.
/// For existing GDSII files with invalid dates, the raw twelve bytes are stored instead.
///
#[derive(Clone, Debug, Deserialize, Serialize, JsonSchema, PartialEq)]
pub enum GdsDateTime {
    /// Valid Date & Time
    DateTime(NaiveDateTime),
    /// Raw Bytes as stored in GDSII
    Bytes([i16; 6]),
}
impl GdsDateTime {
    /// Get the current time
    ///
    /// Note GDSII's time format is specified in seconds, whereas `NaiveDateTime` has nanosecond precision.
    /// Always round to the nearest second to match data coming in from GDSII files.
    ///
    pub fn now() -> Self {
        Self::DateTime(Utc::now().naive_utc().round_subsecs(0))
    }
}
```

**Comment by dan-fritchman** [comment]
Bet lost.  
`Datetime`s are not a part of `GdsLibrary` as of [acd6ac7](https://github.com/dan-fritchman/Layout21/pull/35/commits/acd6ac75f6d9aaefe55ad6b8a8207ca292ab065d), and this still fails. 

Errors have upgraded to: 

```
---- gds_serialization::tests::golden_toml stdout ----
GdsStats { libraries: 1, structs: 1, boundaries: 144, paths: 0, struct_refs: 0, array_refs: 0, text_elems: 10, nodes: 0, boxes: 0 }
thread 'gds_serialization::tests::golden_toml' panicked at 'Could not save output file: values must be emitted before tables', layout21converters/src/gds_serialization.rs:56:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
``` 

We've got an open question with the `toml` authors as to what *should* work here. I think our stuff should? But clearly it doesn't.

**Comment by dan-fritchman** [comment]
https://github.com/toml-rs/toml/issues/396 was recently closed, and updated in TOML v0.6. 
Commit [812ee2d](https://github.com/dan-fritchman/Layout21/commit/812ee2d7f54cbb27eca7ed45588754534b79e058) includes v0.6. It makes the *empty* GDS to TOML work. But the sample in `layout21converters/` continues to fail, now (and after peeling off our own errors) with: 

```
     Running `gds2toml -i resources/sky130_fd_sc_hd__dfxtp_1.gds -o test.toml`
thread 'main' panicked at 'Could not save output file: unsupported GdsElement type', layout21converters/src/gds_serialization.rs:42:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This is hitting TOML's `unsupported_type` function and error-variant. 

Much of the guesswork (by me) thus far on the TOML issue is that this boils down to TOML's "values must come before tables" rule. It seems (from its commentary) that the Rust TOML package should paper over this. But then again maybe not.
